language: node_js
node_js:
  - 9

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -t reddock/poker-seasons .

script:
  - docker run -e CI=true reddock/poker-seasons
