language: node_js
node_js:
  - 9

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -t reddock/poker-seasons .
  - docker run reddock/poker-seasons

script:
  - npm run test
